finalapp/urls.py
from django.urls import path
from . import views
app_name='finalapp'
urlpatterns = [
       path('AddCategory/',views.addcategory,name='addcategory'),
        path('add_category',views.add_category,name='add_category'),
       path('delete_category/<int:categoryid>/',views.delete_category,name='delete_category'),
       path('edit_category/<int:categoryid>/',views.edit_category,name='edit_category'),

]

finalproject/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static

#from hipro import settings
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('finalapp.urls'))
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

finalapp/models.py
from django.db import models

class CategoryMaster(models.Model):
    categoryname = models.CharField(max_length=30)
    categorydescription = models.TextField()
    def __str__(self):
        return self.categoryname

finalapp/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib import auth, messages

from .models import *
app_name='finalapp'

def addcategory(request):
    categories = list(CategoryMaster.objects.all())
    categories.reverse()
    context = {
        'categories': categories
    }
    return render(request,'category.html',context)
def add_category(request):
    categories = CategoryMaster.objects.all()
    if request.method == "POST":
        categoryname= request.POST['categoryname']
        categorydescription = request.POST['categorydescription']
        Categories = CategoryMaster(categoryname=categoryname, categorydescription=categorydescription)
        Categories.save()
        messages.info(request, "Category added Successfully")
        return redirect('finalapp:add_category')
    context = {
        'categories': categories
    }
    return render(request,'category.html',context)
def delete_category(request,categoryid):
    categories=CategoryMaster.objects.get(id=categoryid)
    categories.delete()
    messages.info(request,"Category Deleted Successfully")
    return redirect('finalapp:add_category')
def update_category(request,categoryid):
    categories = CategoryMaster.objects.get(id=categoryid)
    categories.categoryname= request.POST['categoryname']
    categories.categorydescription = request.POST['categorydescription']
    categories.save()
    messages.info(request,"Category updated successfully")
    return redirect('finalapp:add_category')
def edit_category(request,categoryid):
    sel_categories=CategoryMaster.objects.get(id=categoryid)
    categories=CategoryMaster.objects.all()
    context = {
        'sel_categories':sel_categories,
        'categories':categories
    }
    return render(request, 'category.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
<link rel="stylesheet" href="{% static './css/bootstrap.min.css' %}">
        <script src="{% static './js/jquery.min.js' %}"></script>
<script src="{% static './js/popper.min.js' %}"></script>
<script src="{% static './js/bootstrap.min.js' %}"></script>
    <title></title>
       {% block styles %}

      {% endblock %}

  </head>
   <style>
      body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        background-color: #7FB3D5; /* Keep your existing background color */
      }

      .content {
        flex: 1;
      }

      .footer {
        background-color: #154360;
        color: white;
        text-align: center;
        padding: 3px;
          margin-top: auto;
      }
    </style>
  <body style="background-color: #7FB3D5;">
  <div>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#154360;">
  <a class="navbar-brand" href="#">Billing</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
     
         <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
          Masters
        </a>
        <div aria-labelledby="navbarDropdown" class="dropdown-menu">
          
         <a class="dropdown-item" href= "{% url 'finalapp:addcategory' %}">Category Master</a>
          
        </div>
      </li>
        
    </ul>
  </div>
</nav>
  </div>
  <div class="content">
        {% block content %}
        {% endblock %}
    </div>
   <div class="footer">
  <footer class="footer text-center py-2">
    <p>&copy; 2023 Dimarktech Info Solutions. All rights reserved.</p>
  </footer>
  </div>
  </body>
</html>

templates/category.html
{% extends "base.html" %}
{% block content %}

<div class="container mt-3">
    {% for message in messages %}
        <p class="alert alert-success mt-3">{{ message }}</p>
    {% endfor %}
    <div class="row">
        <div class="col-sm-4">
            <h3 class="alert alert-info text-center" style="background-color: #2980B9;color: #FFFFFF;">Category Master</h3>
            {% if sel_categories %}
                <form action="{% url 'finalapp:update_category' sel_categories.id %}" method="post" style="background-color: #1F618D; color: #FFFFFF; padding:15px;">
                    {% csrf_token %}
                    <div>
                        <label for="categoryname">Category Name</label>
                        <input name="categoryname" class="form-control" placeholder="Category Name" value="{{ sel_categories.categoryname }}" type="text">
                    </div>
                    <div>
                        <label for="categorydescription">Category Description</label>
                        <textarea name="categorydescription" class="form-control" placeholder="Category Description" type="text">{{ sel_categories.categorydescription }}</textarea>
                    </div><br>
                     <div style="margin-left: 50px; margin-right: 20px;">
                        <button type="submit" class="btn btn-info">Update Category</button>
                    </div>
                </form>
            {% else %}
                <form action="{% url 'finalapp:add_category' %}" method="post" style="background-color: #1F618D; color: #FFFFFF; padding:15px;">
                    {% csrf_token %}
                            <div>
                                <label for="categoryname">Category Name</label>
                                <input name="categoryname" class="form-control" placeholder="Category Name" type="text">
                            </div>
                            <div>
                                <label for="categorydescription">Category Description</label>
                                <textarea name="categorydescription" class="form-control" placeholder="Category Description" type="text"></textarea>
                            </div><br>
                           <div style="margin-left: 50px; margin-right: 20px;">
                                <button type="submit" class="btn btn-info" style=" width:200px; height: 45px;">Add Category</button>
                            </div>
                </form>
            {% endif %}
        </div>
        <div class="col-sm-8">
            <h3 class="text-center alert alert-info" style="background-color: #2980B9;color: #FFFFFF;">Show Category Information</h3>
            <table class="table table-hover" style="max-height: 300px; overflow-y: auto;  background-color: #1F618D;color: #FFFFFF;">
                <thead>
                    <tr>
                        <th scope="col">Sl.No</th>
                        <th scope="col">Category Name</th>
                        <th scope="col">Category Description</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in categories %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ c.categoryname }}</td>
                            <td>{{ c.categorydescription }}</td>
                            <td><a href="{% url 'finalapp:edit_category' c.id %}" class="btn btn-warning btn-sm">Edit</a></td>
                            <td><a href="{% url 'finalapp:delete_category' c.id %}" class="btn btn-danger btn-sm delete-button">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div></div>
    </div>
  <script>
  document.addEventListener("DOMContentLoaded", function () {
    const deleteButtons = document.querySelectorAll(".delete-button");
    deleteButtons.forEach(function (button) {
      button.addEventListener("click", function (event) {
        event.preventDefault();
        const confirmation = confirm("Are you sure you want to delete?");
        if (confirmation) {
          window.location = event.target.href;
        }
      });
    });
  });
  </script>
  {% endblock %}